<?php

$sql = 'ALTER TABLE `objets` ADD `achetable` TINYINT(3) UNSIGNED NOT NULL DEFAULT \'0\', ADD `prix` MEDIUMINT(5) UNSIGNED NOT NULL DEFAULT \'0\';';

/*

ALTER TABLE `objets` ADD `achetable` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `prix` MEDIUMINT( 5 ) UNSIGNED NOT NULL DEFAULT '0';



*/

?> 
